apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-java
    env: dev
    owner: team3
    version: v1
  name: user-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
      env: dev
      owner: team3
      version: v1
  template:
    metadata:
      labels:
        app: user-java
        env: dev
        owner: team3
        version: v1
    spec:
      containers:
      - image: "registryajv1184.azurecr.io/tripinsights/user-java:1.0"
        imagePullPolicy: Always
        name: user-java
        env:
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: server
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
          - name: http
            containerPort: 80
            protocol: TCP